.github/workflows/python-tests.yml
tox.ini

Currently this just enforces the same stuff that can be fixed automatically with `format`, so it seems like maybe there should be a better way to "single source" those, but this can always be changed later.

Add linting

---

src/zoneinfo/_zoneinfo.py
tests/test_zoneinfo.py

This adds the `only_keys` argument to `ZoneInfo.clear_cache`, which will allow for finer-grained control over the `ZoneInfo` instance cache.
It also refactors some of the cache-related tests.

Improve cache tests and modify clear_cache

---

src/zoneinfo/_zoneinfo.py
tests/test_zoneinfo.py

This adds tests to comply with the guarantees from the PEP about the
properties of the `__str__` and the `__repr__`.

Change guarantees about __str__ and __repr__

---

.github/workflows/python-tests.yml
setup.cfg
tox.ini

This is done in separate jobs mainly to ensure that the test suite also works when `tzdata` is *not* installed.

Add extra, tests for tzdata

---

tests/test_zoneinfo.py

Each Version 2+ file contains an entire Version 1 file at the beginning for backwards compatibility purposes.
This change extracts the version 1 file from each of our version 2 files and drops it to a custom "version 1-only" location, so that we can test `ZoneInfo` populated from Version 1 files as well.

Add version 1 tests

---

tests/test_zoneinfo.py

This is a long-running bug in coverage that manifests in many ways. When
the peephole optimizer eliminates a part of the code, it doesn't leave a
trace that coverage can see, so even if a line's effects are seen, the
code shows as uncovered.
It appears that this is happening here, but we can disable the optimizer
in this test by assigning to a random variable to force the branch to be
executed in a way that coverage can see it.
We could also add # pragma: nocover here, but I'd like to make sure that
this line is seen as covered, since otherwise it may mean that some of
our tests are erroneously being treated as folds or gaps.
More background reading:
- bpo-2506 https://bugs.python.org/issue2506
- https://github.com/nedbat/coveragepy/issues/772

Disable peephole optimizer on branch

---

src/zoneinfo/_zoneinfo.py
tests/test_zoneinfo.py

I had not updated the reference implementation to actually do what the PEP says to do with regards to pickles.
I am not a pickle expert or anything, it seems like `__reduce__` is the way to go here, but maybe there's a better option?
I have not really seriously started optimizing for speed here, because I fully intend to create a C implementation as well, so the pure Python version.

Pickle behavior

---

src/zoneinfo/_zoneinfo.py

The PEP has been updated to remove PYTHONTZPATH_APPEND as it's not clear what the use case is and there are some simple shell tricks you should be able to play to accomplish the same thing.

Remove PYTHONTZPATH_APPEND

---

src/zoneinfo/__init__.py
src/zoneinfo/_common.py
src/zoneinfo/_tzpath.py
src/zoneinfo/_zoneinfo.py
tests/test_zoneinfo.py

The tzpath-handling and file IO parts of the code base will be used by both the Python and C extension (at least initially), so they have been moved into their own dedicated private submodules.
To try and comply with 100% diff coverage, I've also gotten these modules to 100% code coverage, and in the process fixed a few other issues:
1. Zero-transition TZif files are now supported, and the TZStr tests have been refactored to take advantage of this.
2. `set_tzpath` now raises `TypeError` instead of `ValueError` if you pass it a string-like value.
3. Setting the `PYTHONTZPATH` variable to "" now correctly sets `TZPATH` to `()`
4. The `zoneinfo.TZPATH` variable is now exposed, using a `__getattr__` mechanism to ensure that it always points to `zoneinfo._tzpath.TZPATH`.

Move tzpath handling and file IO to common submodules

---

src/zoneinfo/_common.py
src/zoneinfo/_zoneinfo.py

Consistently returning `tuple` and using bytes for `tz_str` will both make the implementation of a C extension easier.

Load data return

---

.gitignore
src/zoneinfo/_common.py
src/zoneinfo/_zoneinfo.py
tests/test_zoneinfo.py
tests/test_zoneinfo_property.py
tox.ini

This adds some basic property tests to the repository - this doesn't yet cover any of the behaviors of the ZoneInfo file such as `fromutc` or whatnot.
Eventually we may want to refactor some of the utilities in `test_zoneinfo.py` into a common file, but for now I'd prefer to leave them in `test_zoneinfo` since it's not yet clear if the hypothesis tests will be able to make the transition to the standard library.
The seemingly unrelated changes come from bugs that are immediately revealed from trying to construct arbitrary ZoneInfo files.
@Zac-HD - Do you mind giving this a review? Once this project gets migrated into the standard library, we may want to migrate these tests into Zac-HD/stdlib-property-tests.

Add property tests

---

.github/workflows/python-tests.yml

Without this, sometimes the Windows jobs will fail but still report success.

Separate tests and coverage upload.

---

src/zoneinfo/_common.py
src/zoneinfo/_zoneinfo.py
tests/test_zoneinfo.py

The biggest issue here is that it seems the TZData tests never "worked" properly because they were almost always hitting the cache, which was populated in earlier tests using the same keys. This was determined when the C extension was failing for the property tests but not the `TZDataTest` tests, and it seems important enough to "backport" it to the master branch before the C extension is ready.
This also moves `_load_tzdata` into a `_common` module, rather than trying to duplicate this logic in C, which wouldn't be so hard but it would likely be tedious.

Move tzdata loader into _common and fix tests

---

tests/test_zoneinfo.py

There were several errors here that were not caught because file_size was always much larger than the actual size of the file, so these files were being included whole and unmodified. The results were likely not affected much because by changing the header to a Version 1 header, the Version 2 file was ignored.

Fix version 1 conversion routine

---

src/zoneinfo/_common.py
tests/test_zoneinfo.py

According to RFC 8536 §3.1, the version indicator for version 1 files is '\0' (0x00) (NUL), rather than '1' (0x31) — which makes sense, since the version number was likely added using one of the reserved header bytes.
This version of the code will support `0x00` and also any erroneous files with `TZif1` as the header (though it appears that there was never a version of zic that would generate files with that version number).

Support TZif\0 instead of TZif1

---

src/zoneinfo/_zoneinfo.py
tests/test_zoneinfo.py

Some Version 2+ files have empty TZ strings, which means that the behavior after the last transition is undefined. For now, we will fall back to "hold the last active value", though "use the last STD value" would also be a reasonable and valid choice. In practice, these may not be terribly different.
This also adds a few more tests to round out both types of invalid TZ string and a few more types of *valid* TZ string.

Specify empty TZ string behavior and add more tests

---

tests/test_zoneinfo.py

These are basically stored as global singletons, so it is not prudent to have them also be mutable.

Make test dataclasses frozen

---

pyproject.toml
tox.ini

One of the main inconsistencies with black is the multi-line output, so black will try to write:
```python
from module import (
x,
y,
z,
)
```
But isort will try to write:
```python
from module import x, y, z
```
This makes it impossible to pass `--check` with both tools.
I've also included a few other changes to the isort configuration that were mostly stolen from the attrs project.

Configure isort to be compatible with black

---

src/zoneinfo/_zoneinfo.py
tests/test_zoneinfo.py

The original implementation would always point to the same dictionary, meaning that subclasses of `ZoneInfo` would be sharing the same cache as `ZoneInfo`.

Add subclass support to Python implementation

---

src/zoneinfo/__init__.py

If we import zoneinfo._tzpath on demand, there's the possibility that some import trickery means that `set_tzpath` for this instance of the zoneinfo module points to a different `_tzpath` module than the one we get from a fresh import. Best to make the module self-contained.

Eagerly import _tzpath in zoneinfo module

---

.clang-format
.github/workflows/python-tests.yml
.gitignore
.pre-commit-config.yaml
codecov.yml
lib/zoneinfo_module.c
scripts/upload_codecov.py
setup.cfg
setup.py
src/zoneinfo/__init__.py
tests/_support.py
tests/test_zoneinfo.py
tests/test_zoneinfo_property.py
tox.ini

Originally this was just a stub, but I guess now it's a full-on feature branch, because I keep doing fixup commits to the implementation.
Remaining things to do:

C Extension

---

lib/zoneinfo_module.c
src/zoneinfo/_zoneinfo.py
tests/test_zoneinfo.py
tests/test_zoneinfo_property.py

This is one of those helpful situations where we have two implementations of the same logic that should have exactly the same result, so we can feed it any arbitrary input and test that the two are consistent.
@Zac-HD This might be useful to mention in your language summit presentation. If `test.support.import_fresh_module` were less touchy, I'd be all over this for `datetime`, and this whole class of tests is super useful for anything with both a C and Python implementation, for PEP 399 compliance. That includes, I believe, `heapq`, `json` and `warnings`, plus any new modules that have a C extension.

Add "consistency" property tests

---

lib/zoneinfo_module.c
src/zoneinfo/__init__.py
src/zoneinfo/_tzpath.py
src/zoneinfo/_zoneinfo.py
tests/_support.py
tests/test_zoneinfo.py
tests/test_zoneinfo_property.py

These names were changed in the PEP, but hadn't been updated in the implementation yet.
Closes #31.

Rename methods to be consistent with PEP

---

.clang-format
lib/zoneinfo_module.c

This is apparently required on AIX:
https://github.com/pganssle/zoneinfo/issues/37
Apparently the previous `.clang-format` file was enforcing that "Python.h" go after the standard library headers, so I've turned off include sorting.
@isidentical Do you have access to an AIX system? Would you mind checking that this has fixed the problem?
Fixes #37.

Move the Python.h declaration to the top.

---

lib/zoneinfo_module.c
tests/data/zoneinfo_data.json
tests/test_zoneinfo.py

Prior to this change, when a zone has a single transition (particularly to a zone with no DST), the fold handling logic in the C extension was broken, because the logic for detecting how to handle the first offset was incorrectly based on the number of transitions rather than the number of ttinfos.
This bug was discovered by running the property tests over and over again hundreds of times; the minimal reproducing case has also been added to the unit tests.
@Zac-HD This is another one for the trophy case, if you're still collecting stuff caught prior to merge (though if I exposed the transitions for each zone, I think I could have found this by exhaustive testing, because there are only ~121k transitions across ~1800 time zones available on my machine).

Fix fold inconsistency

---

tests/test_zoneinfo.py
tests/test_zoneinfo_property.py
tox.ini

Using the [`pytest-randomly`](https://github.com/pytest-dev/pytest-randomly) plugin allows us to run the tests in a random order, to avoid accidental dependencies on the run order of the tests.
As part of adding this to the test suite, I ran the test suite several hundred times and fixed all the issues that cropped up. Likely we will want to follow this up with a CI job that just runs the test suite a few hundred times once a day or once a week or so.
This also adds `pytest-xdist`, which runs the tests in parallel. It's not enabled on CI at the moment, but it does speed things up a bit when running the tests over and over again in a loop.

Start testing in random order (and fixes to allow this)

---

src/zoneinfo/__init__.py
src/zoneinfo/_common.py
src/zoneinfo/_tzpath.py
tests/test_zoneinfo.py

This will hopefully prevent any attempt to specify zoneinfo files outside of TZPATH.
This also makes the distinction between `ZoneInfoNotFoundError`, which is for missing keys and a plain `ValueError`, which is used for a key that we reject as invalid.
Right now I am not enforcing that the key be considered valid when passed to `ZoneInfo.from_file(..., key=key)` because that `key` is not used to look up any files (it's just the name for the zone), but maybe we should?
Fixes #44.
Maybe @tiran - would you be willing to take a look at this, since it is one of the only "security" things in [PEP 615](https://www.python.org/dev/peps/pep-0615/#security-implications)?

Add further validation to keys

---

lib/zoneinfo_module.c
src/zoneinfo/_zoneinfo.py
tests/test_zoneinfo.py
tests/test_zoneinfo_property.py

Per the documentation, `.utcoffset()`, `.dst()` and `.tzname()` should return None when the offset is unknown; for anything with transitions, a datetime.time() is not enough information to resolve the offset.
For fixed offset zones, we know the right response - though I believe this will not correctly handle a "permanent DST" zone like "XST0XDT,0/0,J365/25", which looks like it has transitions but doesn't.
Luckily, that sort of thing doesn't exist in the time zone database, and even if it were added "can't get the offset from datetime.time" is not a big deal.
Closes #33 and #34.

Add time support

---

src/zoneinfo/__init__.py
src/zoneinfo/_tzpath.py
tests/test_zoneinfo.py

Per PEP 615, only absolute paths are allowed in TZPATH; the behavior is up to the implementation, but it must either ignore, warn + ignore or raise.
We choose to warn for the environment variable and raise for `reset_tzpath(to=...)`.
This is related to / the inverse of #44.

Handle relative paths in TZPATH

---

src/zoneinfo/__init__.py
tests/test_zoneinfo.py
tests/test_zoneinfo_property.py

Irritatingly, codecov silently stopped responding to web hooks or something a while back, and the code coverage has decayed from 100% down to some lower number. This PR should bring us back into line.

Improve code coverage

---

.github/workflows/python-tests.yml
.gitignore
docs/conf.py
docs/index.rst
docs/requirements.txt
docs/zoneinfo.rst
tox.ini

This is a first draft of the module documentation.
Minimum requirements:
Deferred for later expansion:
- A section on the cache behavior and how it affects the semantics of datetimes
- Documentation of the [behavior during data updates](https://www.python.org/dev/peps/pep-0615/#behavior-during-data-updates) (though that may be subsumed into the section on the cache behavior).
- Set up some sort of docs-building CI
I've set up RTD to render the documentation [here](https://zoneinfo.readthedocs.io/en/documentation); the main documentation is [in the module documentation](https://zoneinfo.readthedocs.io/en/documentation/zoneinfo.html).
Closes #35.

Add documentation

---

.github/workflows/python-tests.yml
MANIFEST.in
pyproject.toml
setup.cfg
src/zoneinfo/__init__.pyi
tests/typing_example.py
tox.ini

This adds type stubs and also has some minor fixes to the sdist builder.
The type stubs are for eventual inclusion in typeshed.

Add type stubs

---

setup.cfg

tzdata has moved into the python organization, so until we make a release, the extra needs to point at the tzdata repo.

Update tzdata link to new home

---

.pre-commit-config.yaml
setup.cfg

This is not currently added to the GHA or to `tox -e format`, but I have been so spoiled by auto-formatters that I really don't want to have to think about consistent formatting anymore.

Add setup.cfg formatter

---

.github/workflows/python-tests.yml
lib/zoneinfo_module.c
tox.ini

While migrating this over the CPython, I noticed it was raising several warnings enabled in that repo.
This PR fixes those issues and improves our testing for various C-level issues.

Increase C strictness

---

src/zoneinfo/_zoneinfo.py
tests/test_zoneinfo_property.py

This makes the outputs and the reprs more uniform. Not exactly a recommended workflow, but it also makes it so that you can pickle a ZoneInfo in one version and unpickle it in the other.

Give pure Python module the same module as C

---

docs/zoneinfo.rst
lib/zoneinfo_module.c
src/zoneinfo/__init__.py
src/zoneinfo/_common.py
src/zoneinfo/_tzpath.py
src/zoneinfo/_zoneinfo.py
tests/test_zoneinfo.py

This includes various updates to this module based on feedback and bugs found in merging this functionality into CPython: https://github.com/python/cpython/pull/19909
Including:
- Refleaks
- Cosmetic changes
- Additional tests
The two can't be kept in perfect sync, unfortunately, because the code layout is different (and thus the relative imports and a few other consequences of that), but we can manually backport things until both codebases reach stability.

Backport changes from CPython PR

---

docs/zoneinfo.rst
src/zoneinfo/__init__.py
src/zoneinfo/__init__.pyi
src/zoneinfo/_tzpath.py
tests/_support.py
tests/test_zoneinfo.py
tests/test_zoneinfo_property.py
tests/typing_example.py

Add a function to retrieve all time zones available on the system.

Add available timezones

---

setup.cfg
tox.ini

We now have release candidates for tzdata available on PyPI, so we can use those as our source for testing. We need to enable `--pre` because old yanked versions exist and `pip==20.1` will choose yanked versions over pre-releases.

Switch extra dependency to tzdata

---

README.md
docs/conf.py
docs/index.rst
docs/requirements.txt
docs/zoneinfo.rst
tox.ini

Now that we've merged #64, this repo is now officially a backport of `zoneinfo`, and we should document it as such.

Update documentation to reflect backport status

---

.github/workflows/build-publish.yml
.github/workflows/python-tests.yml
README.md
docs/index.rst
setup.cfg
src/backports/zoneinfo/_common.py
src/backports/zoneinfo/_tzpath.py
src/backports/zoneinfo/_zoneinfo.py
tests/test_zoneinfo.py
tox.ini

Just a few minor tweaks was all that was necessary for this. The positional-only arguments are not enforced in the pure Python version because it's too much of a hassle :cry:

Add Python 3.7 compatibility

---

.github/workflows/build-publish.yml
.github/workflows/python-tests.yml
README.md
docs/index.rst
lib/zoneinfo_module.c
setup.cfg
src/backports/zoneinfo/__init__.py
src/backports/zoneinfo/_common.py
src/backports/zoneinfo/_tzpath.py
tests/test_zoneinfo.py
tests/test_zoneinfo_property.py
tox.ini

I wasn't sure I was going to do this, but it turned out to be pretty easy, so this module is now also compatible with Python 3.6.

Add Python 3.6 compatibility

---

.pre-commit-config.yaml
pyproject.toml
scripts/benchmark.py
src/backports/zoneinfo/_common.py
src/backports/zoneinfo/_tzpath.py
src/backports/zoneinfo/_zoneinfo.py
tests/test_zoneinfo.py
tests/test_zoneinfo_property.py
tox.ini

`pylint` is useful for some linting rules [but it is way too noisy](https://pythonspeed.com/articles/pylint/), so I've gone with a pretty tightly-scoped whitelist of rules to enable.

Add pylint and delint

---

.github/workflows/build-publish.yml
.github/workflows/python-tests.yml
lib/zoneinfo_module.c

This now enforces that the Windows compiler treats all warnings as errors, except for the "unknown pragma" warning, which is incompatible with the GCC error-disabling pragmas.
I've also disabled one warning about possible precision loss and ensured that the runtime logic prevents precision loss in any of these situations.

Compiler warnings

---

.github/workflows/python-tests.yml
README.md
docs/index.rst
setup.py
tests/_support.py
tests/test_zoneinfo.py

For now this only works with source distributions — I'd like to ship a PyPy wheel, but I can't figure out how to tag it so that it will *only* get picked up on PyPy.
I have an alternate version of this that actually allows the C extension to compile on PyPy, but on PyPy the C extension is way slower than the Python implementation (which for a lot of these benchmarks is actually faster than the C extension on CPython):
```
Running constructor in zone America/New_York
c_zoneinfo: mean: 490.79 ns ± 16.89 ns; min: 468.35 ns (k=5, N=1000000)
py_zoneinfo: mean: 49.54 ns ± 2.07 ns; min: 47.39 ns (k=5, N=10000000)
pytz: mean: 1.71 µs ± 70.73 ns; min: 1.66 µs (k=5, N=1000000)
Running constructor_strong_cache_miss in zone America/New_York
c_zoneinfo: mean: 28.57 µs ± 3.71 µs; min: 24.29 µs (k=5, …
```

Add pypy support

---

.github/workflows/build-publish.yml
.github/workflows/python-tests.yml
lib/zoneinfo_module.c
setup.py

This uses a macro to use the "disable this warning on GCC" pragmas only on GCC, to avoid "unknown pragma" warnings on other compilers.

Refactor error disabling

---

lib/zoneinfo_module.c
tests/test_zoneinfo.py

`__init_subclass__` was not a classmethod, which means that subclassing `ZoneInfo` was impossible. This was missed because the C module "subclass" test case was not actually testing the subclass, and was actually just running the exact same tests as CZoneInfoTest.
Fixes #82 
CC @sdispater

Fix subclassing in C implementation

---

.github/workflows/build-publish.yml
.pre-commit-config.yaml
pyproject.toml
tests/_support.py
tox.ini

`isort` now acts recursively by default, and skips `__init__.py` by default. It apparently also has changed the sort order slightly, so this should now be in compliance.
This also fixes an issue with `docker`.

Upgrade isort to version >=5.0.0

---

lib/zoneinfo_module.c

Reported in CPython [bpo-41025](https://bugs.python.org/issue41025?#msg375530) and [bpo-41568](https://bugs.python.org/issue41568), there are two refleaks related to subclassing the C implementation of `ZoneInfo`:
1. `__init_subclass__` leaks a reference to the subclass's weak cache.
2. `ZoneinfoSubclass.clear_cache()` incidentally sets `zoneinfo.ZoneInfo`'s pointer to its strong cache to `NULL`, thus leaking the old strong cache (and forcing `ZoneInfo` to create a new one).

Fix refleaks in ZoneInfo code

---

.github/workflows/python-tests.yml
.pre-commit-config.yaml
scripts/update_test_data.py
tests/test_zoneinfo.py

I guess `black` changed some of how code is formatting, which is causing the linting CI job to break.
This updates all of our pre-commit hooks along with:
1. Changes to the formatting to match the new `black` style (unfortunately this will probably only be reflected in the CPython source code if we have to touch the reformatted parts anyway).
2. Remove `setup-cfg-fmt`. Considering the fact that it is preventing us from including comments in `setup.cfg` (intentionally) and that it auto-populates the trove classifiers with Python 3.9 — which would be inappropriate to either add to the trove classifiers or forbid using `python_requires` — it's doing more harm than good. We'll just have to be diligent about formatting unless we find something better.

Update pre commit hooks and remove setup-cfg-fmt

---

.github/workflows/python-tests.yml

When it's just me pushing branches directly to my own namespace there is no difference, but I think this makes it so that the tests aren't triggered when someone else makes a PR.

Run test workflow on PR, not push

---

.github/workflows/build-publish.yml
tox.ini

Apparently there was some CVE for `set-env`. I am not terribly worried about this, but the solution of putting the environment variable definitions into a file seems simple enough.

Migrate build action to use environment files

---

.github/workflows/python-tests.yml
lib/zoneinfo_module.c

It is annoyingly difficult to suppress these unnecessary warnings, but adding a static assertion about the type of the variable `day` essentially accomplishes the same goal (even if it does so only on one compiler), so this should solve the problem.

Use static type assertion in place of warning suppression

---

lib/zoneinfo_module.c

See https://bugs.python.org/issue42697 for more info

Decrement the refcount of PyLong_FromLong(1) in the correct branch

---

scripts/update_test_data.py
tests/data/zoneinfo_data.json
tests/test_zoneinfo.py

Historical updates to Australia/Sydney would break the tests starting with 2020e. This leads to a discrepancy between how the test suite fairs with the latest `tzdata` installed and the pinned data we've vendored.
The relevant commit on github.com/eggert/tz is 1aca4cad3692063cd5cb571883ccf6d04b3c2991
https://mm.icann.org/pipermail/tz/2020-November/029496.html
This updates the pinned data and our tests.

Update zoneinfo tests and test data

---

.github/workflows/build-publish.yml

Add aarch64 wheel build support.
Related to https://github.com/pganssle/zoneinfo/issues/99  @pganssle Could you please review this PR?

Add aarch64 wheel build support

---

.github/workflows/build-publish.yml
scripts/build_manylinux_wheels.sh
tox.ini

`pep517.build` is deprecated and pypa/build is ready, so we can and should switch over now.
Replaces #91

Use pypa/build in favor of pep517.build

---

.github/workflows/python-tests.yml

It seems that https://foss.heptapod.net/pypy/pypy/-/issues/3331 and https://github.com/tox-dev/tox/issues/1704 have been closed for some time now, and the changes should be rolled out to Github Actions by now 🤞.
Replaces #95, which has a workaround that shouldn't be needed anymore.

Re-enable PyPy tests on Windows

---

.github/workflows/build-publish.yml
.github/workflows/python-tests.yml
docs/conf.py
src/backports/zoneinfo/_tzpath.py
src/backports/zoneinfo/_zoneinfo.py
tests/test_zoneinfo.py
tests/typing_example.py

This PR updates PR https://github.com/pganssle/zoneinfo/pull/127, and gets the CI running again for Python 3.6. 
The "Build and release" workflow now passes, and the "Python package" workflow has failing tests, but it's progress! At least they're running! 🚀 
Things done here:
* Bump GitHub Actions versions
* Allow all jobs to continue if one fails: to see which pass, which need fixes
* Update the matrix so EOL Python 3.6 is run using older (deprecated) runners
* Apply Black formatting to fix part of linting
---
A quick look at some failures:
```
File "/home/runner/work/zoneinfo/zoneinfo/.tox/py/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
exec(co, module.__dict__)
File "/home/runner/work/zoneinfo/zoneinfo/.tox/py/lib/python3.7/site-packages/hypothesis …
```

Fix some GitHub Actions things

---

docs/conf.py

Apparently there was a change in Sphinx around 6.1.3 that doesn't allow for the implicit `%s` substitution at the end of the string. See: https://github.com/sphinx-doc/sphinx/issues/11094

Add %s to extlinks

---

tests/test_zoneinfo.py

It is possible but unlikely for the `python_tzpath_context` function to fail between the start of the `try` block and the point where `os.environ.get` succeeds, in which case `old_env` will be undefined. In this case, we want to take no action.
Practically speaking this will really only happen in an error condition anyway, so it doesn't really matter, but we should probably do it right anyway.
This will also fix the `lint` CLI, which has apparently just recently started noticing that there's a potential used-before-assignment error here.

Handle check for PYTHONTZPATH failing
